import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const wasmPath = resolve(__dirname, '../pkg/pic_match_bg.wasm');
const outputPath = resolve(__dirname, '../src-ts/wasm-binary.ts');

const wasmBytes = readFileSync(wasmPath);
const base64 = wasmBytes.toString('base64');

const content = `// Auto-generated by scripts/embed-wasm.ts
// Do not edit manually
export const WASM_BINARY = '${base64}';
export const WASM_BINARY_LENGTH = ${wasmBytes.length};
`;

writeFileSync(outputPath, content);
console.log(`Embedded WASM binary (${wasmBytes.length} bytes) to ${outputPath}`);
